### ISSUE TITLE
Adding category fails

### ISSUE THREAD

**Issue by blinkcursor** [caleb531/awesome-cpt#1]
I've used awesome-cpt on a few projects (thanks!).

On the current project I wanted my CPT 'event' to be able to use the in-built categories (i.e. not a custom taxonomy), and so I added the 'taxonomies' argument to my CPT declaration:

```
$event = new Awesome_Post_Type( array(
  'id'   => 'event',
  'name' => array(
      'singular' => 'event',
      'plural'   => 'events'
  ),
  'args' => array(
      'menu_icon'     => 'dashicons-calendar-alt',
      'menu_position' => 20,
      'supports'    => array( 'title', 'editor', 'thumbnail', 'page-attributes' ),
      'has_archive' => 'events',
      'taxonomies'  => array('category','post_tag')
  )
) );
```

(I threw tags in for good measure.)

Categories (or tags) failed to show up on the edit event pages.

So I resorted to directly registering it with 
    register_taxonomy_for_object_type( 'category', 'event' );
and that worked as expected...

**Comment by caleb531** [comment]
Hi, @terraling. Thanks for letting me know about this issue. :)

I have reviewed your proposed change and all looks good to me. I've tweaked the plugin on (`feature/taxonomies` branch) to automatically register any taxonomies you pass to the `taxonomies` argument. Please test the changes and let me know how it works for you.

When you confirm that the changes work, I'll merge this into the main branch and create a new release. :)

Thanks,
Caleb
